### ISSUE TITLE
Notification for end-of-month rewards

### ISSUE THREAD

**Issue by iGorTha** [Azuriom/Plugin-Vote#102]
Salut,

Comme demandé dans ma dernière issue concernant l'ajout des récompenses de fin de mois, j'ai remarqué, avec des membres de mon projet, qu'ils n'ont pas reçu leur récompense à la fin du mois.

Serait-il aussi possible d'ajouter une option dans la configuration pour envoyer une notification sur le site aux joueurs figurant dans le classement en fin de moi quand il gagne leurs récompenses, et permettre de modifier le message de cette notification ?

Merci d'avance pour votre aide.

**Comment by MrMicky-FR** [comment]
Added in 01531555ae525cfc3e69bfc7e21660651a15e528
