### ISSUE TITLE
Support for meilleurs-serveurs.com

### ISSUE THREAD

**Issue by RaphaelGF11** [Azuriom/Plugin-Vote#103]
Could you add support for the meilleurs-serveurs.com voting site, please?
Docs: [https://meilleurs-serveurs.com/api/v1/docs](https://meilleurs-serveurs.com/api/v1/docs)

**Comment by MrMicky-FR** [comment]
Due to the important number of **French** websites already supported (over 15), we won’t add more ourselves, but a working pull request would be accepted :)
