### ISSUE TITLE
Automatic rewards at the end of the month

### ISSUE THREAD

**Issue by Maxlego08** [Azuriom/Plugin-Vote#16]
Be able to add and configure the rewards that users will receive at the end of the month when resetting the voting ranking.

You have to be able to:
* Earn points for the plugin shop
* Be able to send multiple commands to the server
* To be able to display information about the winnings in the voting page, the different themes will have to be updated.

**Comment by DuckyDou** [comment]
Any news about that?

**Comment by MrMicky-FR** [comment]
> Any news about that?

Like all suggestions, no

**Comment by MrMicky-FR** [comment]
Never give up, after 2 years it's finally here 🎉
