### ISSUE TITLE
SteamID instead of Username

### ISSUE THREAD

**Issue by Doldak** [Azuriom/Plugin-Vote#20]
integrate {STEAMID} instead of {player} ?

**Comment by MrMicky-FR** [comment]
You can already use:
- `{steam_id}` for the **SteamID 64** of the player (eg `76561198048368658`) 
- `{steam_id_32}` for the **SteamID 32** of the player (eg `STEAM_0:0:44051465`)

**Comment by MrMicky-FR** [comment]
Duplicate of Azuriom/Azuriom#72
