### ISSUE TITLE
Ajouter des options dans le plugin Vote

### ISSUE THREAD

**Issue by B2s88** [Azuriom/Plugin-Vote#31]
fr:

Bonjour, pour le plugin Vote,
peut-on faire des récompenses selon le rang et non selon un Pourcentage
car je pense que tout les mois le plugin logiquement ?. donc voila mon idée à rajouter

exemple:

1er du mois =reward pos 1
2 ieme =reward pos 2
3 ieme =reward pos 3
etc etc etc...

tout ça en automatique récompenses / mois

le system de vote fonctionne bien mais le system de récompense n'est pas complet encore

en:

Hello, for the Vote plugin,
can we make rewards according to the rank and not according to a Percentage
because I think that every month the plugin logically ?. so here is my idea to add

example:

1st of the month =reward pos 1
2nd =reward pos 2
3rd =reward pos 3
etc etc etc...

all this in automatic rewards / month

the voting system works well but the reward system is not complete yet

**Comment by MrMicky-FR** [comment]
Quelles seraient les différences avec l’issue #16 ?

**Comment by B2s88** [comment]
j'ai pas compris votre sens de votre phrase ?

**Comment by MrMicky-FR** [comment]
Ca a visiblement déjà été proposé dans l’issue #16 (👈 c’est un lien, il faut cliquer), donc je demande s’il y a des différences avec ce qui a été proposé dans l’issue #16 ou si c’est la même chose

**Comment by B2s88** [comment]
ha oui 2020 ca sera jamais fait alors bye

**Comment by MrMicky-FR** [comment]
Oui je suis d’accord avec vous. C’est franchement une honte d’avoir un service gratuit qui ajoute régulièrement des suggestions (pour s’en convaincre suffit de regarder le salon annonces du Discord) mais qui n’est même pas capable d’ajouter **toutes** les suggestions proposées…

Après au hasard, si on perdait moins de temps à transférer les issues qui sont créées dans le mauvais repo ou qui sont en double (vraiment au hasard), on aurait peut être plus de temps pour ajouter les suggestions ?

**Comment by MrMicky-FR** [comment]
Duplicate of #16

**Comment by B2s88** [comment]
dsl si vous êtes déborder en 2 ans mon post va vous retardé encore d'une semaine ou mois vraiment désoler Mr
