### ISSUE TITLE
Suggestion: Discord Webhooks

### ISSUE THREAD

**Issue by Axtazer** [Azuriom/Plugin-Vote#32]
Hello! I propose to have a possibility that when a vote is done to have a message by webhooks on a server discord can be sent with a customizable message.

**Comment by MrMicky-FR** [comment]
This would certainly trigger Discord rate limit on large websites :/

**Comment by Doldak** [comment]
> e a possibility that when voting a message can be sent via webhook to a Discord server with a customizable message.

a typical answer after the motto: i have no bock
