### ISSUE TITLE
Bug with {player} function.

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Plugin-Vote#34]
Bonjour ! 🇫🇷 

J'ai remarqué il y a quelques jours l'existance de la fonction {player} pour directement intégrer le pseudo du joueur sur le site du vote. Mais du coup ça ne fonctionne pas. Quels étapes sont à réproduire pour avoir le bug ?

1. Avoir Azuriom V1.0.2,
2. Avoir le plugin vote V1.0.2 également,
3. Aller dans l'onglet "Sites" du plugin Vote,
4. Essayer avec un site compatible (SMV par exemple),
5. Rajouter `?pseudo={player}` à la fin du lien,
6. Résultat : Une fois arrivé sur le site, ça met {player} dans la case "Pseudo" au lieu du pseudo du joueur sur le site.

_J'ai essayé avec le [site de votes](https://serveur-minecraft-vote.fr/) crée par @Maxlego08 et il m'a certifié que ça fonctionnait._

---------

Hello ! 🇺🇸

I found out a few days ago that there is a {player} function to directly integrate the player's nickname on the voting site. But it doesn't work. What steps are to be repeated to get the bug?

1. Have Azuriom V1.0.2,
2. Have the voting plugin V1.0.2 too,
3. Go to the "Sites" tab of the Vote plugin,
4. Try with a compatible site (SMV for example),
5. Add `?pseudo={player}` at the end of the link,
6. Result: When you arrive on the site, it puts {player} in the "Nickname" box instead of the player's nickname on the site.

I tried with the [voting site](https://serveur-minecraft-vote.fr/) created by @Maxlego08 and he certified me that it worked.

----------
~ @Noltox ~

**Comment by MrMicky-FR** [comment]
Fixed in https://github.com/Azuriom/Plugin-Vote/commit/0c397ad92c8348680858ca5c7f9d9ae1f186fc27
