### ISSUE TITLE
Pre-fill username from URL

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Plugin-Vote#40]
Bonjour ! 🇫🇷 
Voici ma **nouvelle idée** pour le plugin vote d'**Azuriom** :

Ajouter le support de la fonction `https://tonsite.fr/vote?pseudo=Pseudo` qui permettrait de directement ramener vers la page de vote du pseudo indiqué dans l'URL sans devoir passer par la page où il faut remplir le pseudo.

 **Pourquoi cette fonctionnaltié serait utile ?**
- Cette fonctionnalité éviterait le fait de se connecter avec Microsoft car la connexion avec le système actuel est un peu foireuse,
- Elle permettrait de directement donner le lien avec le pseudo du joueur pré-rempli dans le tchat Minecraft avec PAPI en faisant par exemple `https://tonsite.fr/vote?pseudo=%player_name%`,
- Elle permettrait de mettre en favoris sa page de vote avec son pseudo.

*Si vous avez des questions à propos de ma suggestion, vous pouvez laisser un commentaire sous cette issues.

Bonne journée,
~ Noltox ~

-----------
Hello ! 🇺🇸
Here is my **new idea** for the **Azuriom** voting plugin:

Add support for the `https://website.fr/vote?pseudo=Pseudo` function which would allow to directly bring back to the voting page of the nickname indicated in the URL without having to go through the page where you have to fill in the nickname.

 **Why would this feature be useful?**
- This feature would avoid the need to connect with Microsoft because the connection with the current system is a bit messy,
- It would allow to give directly the link with the nickname of the player pre-filled in the Minecraft chat with PAPI by doing for example `https://website.fr/vote?pseudo=%player_name%`,
- It would allow you to bookmark your voting page with your nickname.

*If you have any questions about my suggestion, you can leave a comment under this issue.

Have a nice day,
~ Noltox ~

**Comment by MrMicky-FR** [comment]
Added with the `?user=` parameter. 

> Microsoft because the connection with the current system is a bit messy

A better solution would be to open a proper issue about this with more details on [Azuriom repo](https://github.com/Azuriom/Azuriom/issues) :)

**Comment by laboriens** [comment]
je sais que cela est fermer, et je vous qu'il a étais implementer, mais ce serai bien aussi de mettre le steamid pour le site avec steamid

I know it's closed, and I tell you that it was an implementer, but it would also be nice to put the steamid for the site with steamid
