### ISSUE TITLE
Pre-fill steamid from URL

### ISSUE THREAD

**Issue by laboriens** [Azuriom/Plugin-Vote#42]
hello, it's in the same line as this issues https://github.com/Azuriom/Plugin-Vote/issues/40

it will be for qites that use the steamid and have a voting system that allows the steamid to be added to the url (like https://gmod-servers.com/api/?action=post&object=votes&element=claim&key={ServerKey}&steamid={SteamID} 
)

**Comment by MrMicky-FR** [comment]
Added with the `?uid=` URL parameter :)
