### ISSUE TITLE
Automatic page refresh after vote

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Plugin-Vote#43]
🇫🇷 Salutations la communauté Azuriom !
Aujourd'hui je vous propose ma nouvelle petite idée d'amélioration qui est le **rafraîchissement automatique de la page**, je m'explique :
Lorsqu'on veut valider un vote actuellement c'est juste un rectangle sur lequelle on clique pour vérifier le vote mais une fois le vote vérifié, le timer ne s'affiche pas directement, on est obligé de rafraichir la page.
**Ce que je propose donc c'est qu'une fois que le vote est vérifié cela affiche le timer du vote en question.**

~ Noltox ~

------

🇬🇧 Hellow !
Today I propose you my new small idea of improvement which is the **automatic refreshment of the page**, I explain myself:
When you want to validate a vote currently it's just a rectangle on which you click to check the vote but once the vote is checked, the timer is not displayed directly, you have to refresh the page.
**What I propose is that once the vote is verified it displays the timer of the vote in question.**

~Noltox ~

**Comment by MrMicky-FR** [comment]
Added in 03c9fdd399a518b8d0bf81e5ad99dd9c96c24fa8, and even without a page refresh (so the user doesn't need to enter the username again) 😃
