### ISSUE TITLE
Feature request: Execute a command when a vote is available

### ISSUE THREAD

**Issue by NoltoxGit** [Azuriom/Plugin-Vote#45]
🇫🇷 **Bonjour me voici avec une nouvelle suggestion pour le plugin Vote !**
J'ai eu l'idée d'une nouvelle fonctionnalité pour le plugin Vote d'Azuriom qui aurait comme objectif d'envoyer des commandes lorsqu'un vote est disponible sur le site.

### Où pourrait-on ajouter ces commandes ?
Après multiples réfléxions, je me suis dis que ça pourrait bien avoir sa place dans l'onglet "Paramètres" en dessous des cases pour les "Commandes globales".

---> Si vous avez des retours à faire sur ma proposition, je suis ouvert à toutes réponses !

------------
🇬🇧 **Helloww, here I am with a new suggestion for the Vote plugin!**
I had the idea of a new feature for Azuriom's Vote plugin that would have the purpose of sending orders when a vote is available on the site.

### Where could we add these commands?
After many reflections, I thought it could be in the "Settings" tab under the "Global Commands" fields.

---> If you have any feedback on my suggestion, I'm open to any answer !

**Comment by MrMicky-FR** [comment]
Malheureusement je crains que cela risque d’être compliqué à mettre en place au niveau de la gestion multi-serveurs :|
