### ISSUE TITLE
Add an image for the rewards

### ISSUE THREAD

**Issue by Sloyni** [Azuriom/Plugin-Vote#46]
### Description of your suggestion

Add image field for vote plugin rewards

### Advantages

This will display reward images instead of just text.

**Comment by MrMicky-FR** [comment]
An image of this suggestion would be great

**Comment by Sloyni** [comment]
![image](https://user-images.githubusercontent.com/46792072/188117924-b8d10a3a-4966-42fc-b0bc-2b8057867035.png)
![image](https://user-images.githubusercontent.com/46792072/188117963-bd78a73e-957d-4500-b84d-bba2a7b0accc.png)
![image](https://user-images.githubusercontent.com/46792072/188118015-2c412e33-b189-4340-a7f3-61f99392482a.png)
