### ISSUE TITLE
Add Verification for Plugin Vote

### ISSUE THREAD

**Issue by SimonMage** [Azuriom/Plugin-Vote#50]
Hi, could you add verfication support these italian voting sites?
https://minecraft-italia.net/lista/
https://www.minecraft-italia.it/lista-server-java-edition/

**Comment by MrMicky-FR** [comment]
Is there any API to verify votes on these websites ? Because I can’t find one

**Comment by SimonMage** [comment]
This (https://www.minecraft-italia.it/lista-server/documentazione) is the API for https://www.minecraft-italia.it/lista-server-java-edition/ - It is in italian


The other site uses a custom made plugin add-on for Votifier, every server has a Votifier API on his server page,
This is the italian guide; https://minecraft-italia.net/threads/come-installare-minecraft-italia-votifier.123/
for this site https://minecraft-italia.net/lista/

**Comment by SimonMage** [comment]
@MrMicky-FR Any update?

**Comment by MrMicky-FR** [comment]
It’s been 3 days so no. Like all suggestions, there is absolutely no ETA, but if you need this quickly, the project is open source so you can just contribute to it, or find someone who can do it

**Comment by SimonMage** [comment]
I noticed that you added https://www.minecraft-italia.it/lista-server-java-edition/
But https://minecraft-italia.net/lista/ not, could you also add it please?
