### ISSUE TITLE
Add a feedback or a tracking inside admin panel.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Plugin-Vote#56]
Can you add feedback so users can know if they received a reward. Also will be good that rewards given to appear in the admin panel. If not is difficult to know if the reward was given and also if the reward is not automatic.

**Comment by MrMicky-FR** [comment]
When the vote is successful users will get an success banner to inform the rewrard was delivered. Implementing mail or notifications for all vote rewards would be pretty spammy

**Comment by Jotiprime** [comment]
Okay, but please add a log when someone receives a reward, is hard to check every vote in DB with ids.
