### ISSUE TITLE
Website 500 Internal Server Error When disabling the plugin.

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Plugin-Vote#57]
When I disabled the vote plugin, the website returns a 500 Internal Server Error. I tested it multiple times, all times the same.

**Comment by Javdu10** [comment]
Before opening issues like that without providing details, please join the discord and ask your question there

We don't have crystal balls and guess why the error happends if you don't provide logs of the error, they are located in storage/logs

**Comment by MrMicky-FR** [comment]
Closing this for now, if the issue persists please post the logs located in `storage/logs` in this issues

**Comment by MrMicky-FR** [comment]
This issue is from the RewardShower plugin, m because you disabled the vote plugin. Moving this to Azuriom repo as disabling a plugin should also disable plugin which depends on this plugin
