### ISSUE TITLE
Add a global vote function

### ISSUE THREAD

**Issue by JoeDalton9027** [Azuriom/Plugin-Vote#58]
I noticed that with the current system when many users vote for the server the in game chat can be spammed.
Especially when recovering votes

The solution could be to have an option that can be activated on request to choose to activate the "spam reduction" mode for example which would send a message every X minutes (configured via the plugin on azuriom) which would have the function of recording the number of votes during the X period and then recording the nickname of the last person who voted.

Which could possibly give this.. "{last_user} and X other people just voted for the server"

I think this addition could be a real asset that other CMS do not have, and I also think that this system can appeal to a good number of users.

Best regards.

**Comment by MrMicky-FR** [comment]
After some reflections it’s seems a little bit out of scope for the vote plugin, as it’s not limited to vote (the same issue could occur with the shop for example) and it can be easily implemented in a in-game plugin
