### ISSUE TITLE
Add received rewards in admin dashboard

### ISSUE THREAD

**Issue by Jotiprime** [Azuriom/Plugin-Vote#59]
Add Discord Webhook to register the votes and also when someone receives a reward.

**Comment by Jotiprime** [comment]
Actually, you need to access the database to see and check if somebody received a reward, no other option will be good than Discord webhook as mentioned includes this.

**Comment by MrMicky-FR** [comment]
This would most likely cause issues with Discord rate-limitation on servers with an important amount of players

**Comment by Jotiprime** [comment]
Okay, if can't be done by discord, add logs to see last votes and last rewards, now we need to access db to check it.

**Comment by Jotiprime** [comment]
![image](https://user-images.githubusercontent.com/73477224/221411190-22bcd570-b4b3-4dd3-9adc-873ae1789c3e.png)

500 Error when accessing "votes" page in admin dashboard.
