### ISSUE TITLE
Add more Vote Sites

### ISSUE THREAD

**Issue by CraftJunkies** [Azuriom/Plugin-Vote#64]
Can you please add support for following sites:

- https://www.minecraft-serverlist.net/
- https://minecraft-server-list.com/
- https://serverlocator.com/
- https://minecraft-servers.de/
- https://www.planetminecraft.com/

**Comment by Certurix** [comment]
I would suggest to add also this new website:

- https://serveurliste.com

**Comment by MrMicky-FR** [comment]
> Can you please add support for following sites:
> 
> * https://www.minecraft-serverlist.net/
> * https://minecraft-server-list.com/
> * https://serverlocator.com/
> * https://minecraft-servers.de/
> * https://www.planetminecraft.com/

The site must offer an API to be able to check the vote, otherwise it is not possible to check the vote. But looks like none of these sites has an API for this

**Comment by CraftJunkies** [comment]
Would it be possible to add them even if they dont provide an api? Would be nice to have all voting links bundeld on one page.....

**Comment by MrMicky-FR** [comment]
> Would it be possible to add them even if they dont provide an api? Would be nice to have all voting links bundeld on one page.....

Yes, it’s already possible, you can add any URL as a voting website, but the vote won’t be verified so the users will always get the rewards

**Comment by CraftJunkies** [comment]
Oh ok i will try again and thank you for replying so fast

**Comment by MrMicky-FR** [comment]
Great, I’m closing this issue as the original question is resolved, but if you have any question feel free to comment back or ask on our Discord server
