### ISSUE TITLE
[SUGGEST] Add Italian website list to available websites

### ISSUE THREAD

**Issue by SimonMage** [Azuriom/Plugin-Vote#71]
Hi, first of all, the other italian website https://minecraft-italia.it has closed, you can remove it from the list.

At the end in Italy we have only one website list, could you please implement it?
This is the website (https://minecraft-italia.net/lista/) but this website has not an API, it works with Votifier plugin, 
Here you can see an example of server page on this website, votes works with votifier. I don't know if you can add it but this is the last server list in Italy, please take it in consideration
![Screenshot_1](https://github.com/Azuriom/Plugin-Vote/assets/75200996/f66f47f7-f237-4e5a-99df-fe496f9463f2)

Regards

**Comment by MrMicky-FR** [comment]
Unfortunately if there is no API we can’t add it 😕
