### ISSUE TITLE
Add verification for minecraft-italia.net

### ISSUE THREAD

**Issue by SimonMage** [Azuriom/Plugin-Vote#72]
Hi, first of all, the other italian website https://minecraft-italia.it/ has closed, you can remove it from the list.

At the end in Italy we have only one website list, could you please implement it?
This is the website (https://minecraft-italia.net/lista/)
Here the API of website https://minecraft-italia.net/lista/docs/

**Comment by MrMicky-FR** [comment]
Added in 4d3a737d87622c824c51845c96753239e480c915

**Comment by SimonMage** [comment]
Could you update the list here https://market.azuriom.com/resources/2 ?
It result Minecraft Italia.it
But it is removed and now there is Minecraft-Italia.net
