### ISSUE TITLE
Add verification for playbase.pro

### ISSUE THREAD

**Issue by RikoDEV** [Azuriom/Plugin-Vote#76]
First of all, thanks for creating such a useful plugin. I would like to suggest adding playbase.pro to the list of supported sites.

The list has an API and from December 1 will require a Bearer API Token to support the following endpoints:

* Info (GET): https://playbase.pro/api/vote/{server}/{ip}
```json
{
  "id": 5143,
  "server": 245,
  "user_id": 0,
  "nickname": "Notch",
  "date": "2022-08-01T18:54:06.000Z",
  "received": false
}
```
* Redeem (POST): https://playbase.pro/api/vote/{server}/{ip}/redeem
```json
{
  "status": 200,
  "response": "Successfully received."
}
```

Swagger: https://playbase.pro/en/api

**Comment by MrMicky-FR** [comment]
Added in above commit, but untested because I can't register on the given website: I have "The field must be accepted." error for TOS and privacy policy, even when checking the box...

**Comment by MrMicky-FR** [comment]
Thanks for the feedback, do you think you could create a pull request with the updated fixed code ? As I can't test it's not convenient 😕

**Comment by RikoDEV** [comment]
> Thanks for the feedback, do you think you could create a pull request with the updated fixed code ? As I can't test it's not convenient 😕

The checkbox during registration is fixed. Actually, problem 2 remains. For some reason `transformRequest` is not receiving User $user, Site $site.

**Comment by MrMicky-FR** [comment]
> For some reason `transformRequest` is not receiving User $user, Site $site. - @RikoDEV 

Could you test by replacing this line
https://github.com/Azuriom/Plugin-Vote/blob/874c82c43a7fe168ec9158a3dfeb22da33792e3d/src/Verification/VoteVerifier.php#L213

With these lines, and tell me if it fixes the issues (or directly open a PR if you prefer):
```php
$request = Http::asJson();

if ($this->transformRequest !== null) {
    $request = ($this->transformRequest)($request, $user, $site);
}

$res = $request->get($url);
```

**Comment by RikoDEV** [comment]
> > For some reason `transformRequest` is not receiving User $user, Site $site. - @RikoDEV
> 
> Could you test by replacing this line
> 
> https://github.com/Azuriom/Plugin-Vote/blob/874c82c43a7fe168ec9158a3dfeb22da33792e3d/src/Verification/VoteVerifier.php#L213
> 
> With these lines, and tell me if it fixes the issues (or directly open a PR if you prefer):
> 
> ```
> $request = Http::asJson();
> 
> if ($this->transformRequest !== null) {
>     $request = ($this->transformRequest)($request, $user, $site);
> }
> 
> $res = $request->get($url);
> ```

Works 👾
![vmplayer_QkxMBZqxQr](https://github.com/Azuriom/Plugin-Vote/assets/18230443/f17671b2-d7d7-47fb-9b42-52425d0f17a5)
