### ISSUE TITLE
Problème avec le plugin Vote / avec Bedrock Connect.

### ISSUE THREAD

**Issue by KvasirQc** [Azuriom/Plugin-Vote#78]
I can translate this post if needed. Sorry it's a copy paste from the discord, I had no answer

Salut tout le monde, je vous ecris pour savoir, avec le plugin de /vote, s'il serait possible d'accepter et de gérer les votes recus par des joueurs bedrock.

Si on indiquait quel préfix dont nous nous servons:  (exemple .devant le nickname)

PS: j'ai tenté sur les sites web des votes, de rajouter le .devant le nick name sans succès. 

Le site web acceptait mon vote, mais le joueur ne recevait pas les rewards voulus.
Ce serait super de pouvoir fix cela svp :)!

**Comment by MrMicky-FR** [comment]
I’m not sure to understand the issue, is this a translation to french ? If yes it would be easier to just post the english message because I’m not sure to understand

**Comment by KvasirQc** [comment]
The bedrock players are not receiving the rewards. Players are using bedrock connect to connect on java player.

Is there anyway that bedrock player, with the prefix . (dot), could receive the rewards please? 

I've tried on different website, to just add the prefix (dot) infront without success..

Thank you have a nice day.

**Comment by MrMicky-FR** [comment]
Using dot in a name usually works fine with Azuriom, do you have any error message or something ?

**Comment by KvasirQc** [comment]
No, the website were accepting the vote, but the rewards were not reaching the player ...sorry.

**Comment by KvasirQc** [comment]
Ok just to let you know, I tried on 10 website, and know feedback from the game. None of the three rewards I've set, even if the website told me I won them.

**Comment by KvasirQc** [comment]
![image](https://github.com/Azuriom/Plugin-Vote/assets/40178706/6288d30b-fb6e-45c3-97e8-2cf584f28207)
I've just logged on my main MC account WeConnected and I received a bunch of rewards...probably some who belongs to .WeConnected710, an account probably link to the same email but bedrock instead of java...

Sorry if it's alot of info and not much clear, that's all I have.

Bon matin!

**Comment by MrMicky-FR** [comment]
Try disabling the option to only send rewards when player is online. But otherwise AzLink makes no difference about a player with a dot or without dot, so not sure of the issue

**Comment by KvasirQc** [comment]
What will happen to the item he gains if he's not connected? The cash I can understand that it would be added to their account, but what about the items.

+

If I use the function that you are telling me, and the player is on a windows bedrock, he won't be able to keep his connection to the server because of bedrock and he won't receive the rewards. Am I mistaken?

Thanks for your help
