### ISSUE TITLE
7 days to Die Voting

### ISSUE THREAD

**Issue by sapdkeybinder** [Azuriom/Plugin-Vote#80]
Hello! Would it be possible to add the voting website "7daystodie-servers.com" for the game 7 Days to Die? Thank you very much!

**Comment by MrMicky-FR** [comment]
Currently 7 Days To Die isn't officially supported by Azuriom so we won't add it for now in the vote plugin. However you can easiy add support by adding `'7daystodie-servers.com',` in the file `plugins/vote/src/Verification/VoteChecker.php` here:
https://github.com/Azuriom/Plugin-Vote/blob/3602eae5b57e9287040354f122103d6c7033aff1/src/Verification/VoteChecker.php#L140-L146

Like this:
```diff
 $listForge = [
     'gmod-servers.com',
     'ark-servers.net',
     'rust-servers.net',
     'tf2-servers.com',
     'counter-strike-servers.net',
+    '7daystodie-servers.com',
 ];
```
