### ISSUE TITLE
Problème potentielle avec le plugin de vote 

### ISSUE THREAD

**Issue by Boulldog0** [Azuriom/Plugin-Vote#81]
Hey !

J'ai remarqué il y'a quelques jours que simplement en changeant d'IP ou en changeant la date de son ordinateur/ téléphone, on pouvais bypass le cooldown des votes, ce qui est assez embêtant quand on donne des récompenses, car c'est clairement du give :/

Y'a t'il quelque chose a faire pour régler ce soucis ?

English Version : 

I noticed a few days ago that simply by changing your IP or changing the date of your computer/phone, you could bypass the vote cooldown, which is quite annoying when you give out rewards, because it is clearly a give :/

Is there anything to do to resolve this problem?

**Comment by MrMicky-FR** [comment]
Il faudrait plus de détails, car la vérification se base sur le compte utilisé ainsi que sur l'IP, et non seulement sur l'IP.

La date/heure du navigateur est utilisée uniquement pour l'affichage du timer sur le bouton de vote, mais lors du vote c'est seulement la date du serveur web qui est prise en compte, donc aucun bypass possible à ce niveau là
