### ISSUE TITLE
add a tier system based on number of votes cast

### ISSUE THREAD

**Issue by FrozerYTB** [Azuriom/Plugin-Vote#82]
my suggestion would be to add a tier system with different rewards for each tier (entirely customizable by the user). my idea is simple: the user votes 10 times, moves on to tier 1, votes, reward : 5 pb (60%)... 25 times, moves on to tier 2, receives 1 key (on), 10 store points (40%), a rank (15%)... and at each completed tier a customizable message is sent to the server. a system like the NationsGlory server voting system (for those in the know).
Don't forget to add a ranking system too!

**Comment by FrozerYTB** [comment]
![Capture d’écran (8)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/71adf76a-b1db-4a0c-bf68-4d552fdd8f75)
![Capture d’écran (9)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/1f13b46f-f9c6-4dd0-ba17-24668e1bf926)
![Capture d’écran (10)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/8e39dd8e-afb2-4359-9316-56ba8fdfa2e9)
![Capture d’écran (11)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/50f9beb0-bb9f-4b4c-83dd-77610ad4f013)

**Comment by FrozerYTB** [comment]
![Capture d’écran (12)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/31ba61fa-9131-41ac-a46e-255fb9e09c89)
![Capture d’écran (13)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/cf724578-c48b-4011-8680-125e724f1c46)
![Capture d’écran (14)](https://github.com/Azuriom/Plugin-Vote/assets/131524378/eb7425e3-a0bf-4e98-a8a9-01e5497e7a40)

**Comment by Javdu10** [comment]
@FrozerYTB There is a premium plugin called "RewardShowers" that fits your use case
