### ISSUE TITLE
Support to new verified websites 

### ISSUE THREAD

**Issue by LuluxClient** [Azuriom/Plugin-Vote#83]
### Description of your suggestion

The issue currently is that there is only 2 english speaking verified server from Azuriom server list and it would be cool to add more of them like:
- https://servers-minecraft.net/cp
- https://minecraft-server.net/
- https://minecraftservers.org/

### Advantages

Since they are verified, players will have to fully vote for the vote to work and not just abuse it

**Comment by MrMicky-FR** [comment]
Yes could definitely be a nice feature ! But I can't find any documentation for a vote verification API, could you please provide one ? Otherwise we can't add a verification

**Comment by LuluxClient** [comment]
> Yes could definitely be a nice feature ! But I can't find any documentation for a vote verification API, could you please provide one ? Otherwise we can't add a verification

Hey I'm currently contacting the website owners in order to get that information since I cannot directly find it on their websites. As soon as I get some answers I'll update this suggestion

**Comment by LuluxClient** [comment]
> Yes could definitely be a nice feature ! But I can't find any documentation for a vote verification API, could you please provide one ? Otherwise we can't add a verification

https://minecraft-server.net/api/docs/
