### ISSUE TITLE
Récompenses ne s'envoient pas sur le bon serveur.

### ISSUE THREAD

**Issue by courat-private** [Azuriom/Plugin-Vote#92]
Bonjour,
J'ai récemment remarqué un bug dans le plugin de vote. Lorsqu'un joueur vote, parfois la commande est envoyée sur d'autres serveurs.
Actuellement, j'ai configuré le plugin pour envoyer la récompense sur le serveur "Proxy", qui est bien configuré. Mais parfois, il se peut que la commande soit envoyée sur le serveur "Factions", alors que je n'ai pas renseigné ce serveur sur la récompense.

Je vous met une capture d'écrans.
Le vote du joueur: https://share.courat.eu/nkj7sapjyG.png
Les serveurs configurés sur la récompense: https://share.courat.eu/VfRYE8DR3F.png
La commande envoyée sur le serveur factions: https://share.courat.eu/2kgc7Pcfjh.png
Le manque de commande sur le proxy, pourtant configuré: https://share.courat.eu/pXO3K7BuMO.png

Les deux serveurs ont des ports différents pour AzLink (20001 & 20003).

J'espère que ce rapport est plutôt clair, et que le soucis sera bientôt réglé, merci !

**Comment by MrMicky-FR** [comment]
C’est certainement que les commandes de link n’ont pas été faites correctement, il faudrait les refaire en veillant à ne pas mélangés les commandes selon les serveurs

**Comment by courat-private** [comment]
Je viens de refaire la configuration AzLink sur les deux serveurs, je verrais dans l'après-midi si ça recommence, je tiens au courant dans ce thread. Merci

**Comment by courat-private** [comment]
Bug confirmé !
Après avoir reconfiguré proprement mes serveurs avec AzLink, j'ai toujours le même problème. Des commandes qui ne doivent être exécutées exclusivement sur le proxy sont exécutées sur un autre serveur.

@MrMicky-FR
