### ISSUE TITLE
Upgrade the Voting System

### ISSUE THREAD

**Issue by ncuadra03** [Azuriom/Plugin-Vote#93]
This idea isn't new or anything. But inspires me when I was playing mobile games.

Adding a new content where every vote will be a share on social media post. 
After sharing the post link, they will receive the vote point/item.

PS: Only if it is possible to upgrade such way.

**Comment by MrMicky-FR** [comment]
I’m not sure to understand, because sharing every vote on Twitter or Discord for example (or any other social media) would be a massive spam for big servers

**Comment by ncuadra03** [comment]
> I’m not sure to understand, because sharing every vote on Twitter or Discord for example (or any other social media) would be a massive spam for big servers

I didn't think about that. It is not possible to block the IP address every vote as like right now?

**Comment by MrMicky-FR** [comment]
What do you mean by blocking IP address ?

**Comment by ncuadra03** [comment]
By having time delay every vote. 
![image](https://github.com/Azuriom/Plugin-Vote/assets/171517625/f7a24484-1786-43dd-aab0-2204e5caad70)

Right now it has cooldown after voting on GTOP, isn't like that same logic? Idk Im just theorizing. 
![image](https://github.com/Azuriom/Plugin-Vote/assets/171517625/91058c1b-d67e-473a-be67-09705c6a9591)

**Comment by MrMicky-FR** [comment]
Oh I misunderstood your suggestion in the first message 😅 About this suggestion it could be a great addition, but it seems out of scope of the current vote plugin and would be better suited in a dedicated plugin, so I'm closing this for now :)
