### ISSUE TITLE
Add new Voting Site. 

### ISSUE THREAD

**Issue by ncuadra03** [Azuriom/Plugin-Vote#94]
Adding additional sites for other games would be awesome.
This is my suggestions
https://www.xtremetop100.com/
https://www.arena-top100.com/

**Comment by MrMicky-FR** [comment]
Hello, could you send a link to the vote verification API (if there is one) for each site? Thanks

**Comment by ncuadra03** [comment]
I tried to find it, but i don't know. The Api key that I know is your website generated by these sites.

**Comment by MrMicky-FR** [comment]
I also can't find any documentation on an API to check votes. Unfortunately, if there isn't one, it's not possible to add a vote verification system on Azuriom.

I’m closing this for now, but if ever there’s any way to verify vote, please comment here so we can reopen this
