### ISSUE TITLE
Improve verification for HotMC.ru

### ISSUE THREAD

**Issue by BAD7777** [Azuriom/Plugin-Vote#95]
Hello,

Everything works perfectly when using the hotmc.ru site, but the response from hotmc indicates that the data has not been processed. Please note that if the handler does not return a successful response within 24 hours, it will be automatically deleted according to their rules. I kindly request that you fix the script so that HOTMC correctly acknowledges that the data has been processed.

Thank you!
![image](https://github.com/user-attachments/assets/f15b05af-fc1c-4970-a728-92462475a950)
![image](https://github.com/user-attachments/assets/e2b76cac-7f4b-4d16-a41f-08bd9d35d29d)

**Comment by MrMicky-FR** [comment]
I cannot find any documentation on their website, could you please send the documentation on how to correctly process votes with this website? Or alternatively you can directly open a pull request with the fix+. Thanks
