### ISSUE TITLE
Use rewards only for automatic rewards

### ISSUE THREAD

**Issue by iGorTha** [Azuriom/Plugin-Vote#97]
Je voulais mettre en place des récompenses pour les meilleurs voteurs à la fin du mois sur le plugin de vote. Cependant, je constate que je suis obligé de définir un pourcentage de chance d'obtenir cette récompense. Cela signifie que, lorsque les joueurs votent, ils ont la possibilité de recevoir cette récompense, qui était initialement destinée aux meilleurs voteurs du mois.

Serait-il possible de modifier le système pour permettre de créer des récompenses de vote tout en ayant aussi des récompenses spécifiques pour la fin du mois ?

![image](https://github.com/user-attachments/assets/f2f1b214-13a1-43af-ac42-d3bab2a5e405)

**Comment by MrMicky-FR** [comment]
Il est maintenant possible de mettre une chance de 0% pour qu'une récompense puisse être donnée uniquement à la fin du mois (et elle n'apparaitra pas dans la liste des récompenses)

**Comment by Koora7334** [comment]
Ce qui aurait été bien c'est de pouvoir récupérer son nombre de votes total dans la case "argent", et d'y appliquer des formules mathématiques
