### ISSUE TITLE
Review of Voting Sites

### ISSUE THREAD

**Issue by KnightWorldfr** [Azuriom/Plugin-Vote#98]
Hello, to contribute to the development of the voting plugin, I have researched voting sites, from the most known to the least known, that are not detected by Azuriom:

Most known voting sites not verified:
1. serveur-minecraft.com - [https://serveur-minecraft.com/faq/api](https://serveur-minecraft.com/faq/api)
2. minecraft-server-list.com - votifier: [https://minecraft-server-list.com/faq/#what-is-votifier](https://minecraft-server-list.com/faq/#what-is-votifier)
3. minecraftservers.org - votifier: [https://minecraftservers.org/help](https://minecraftservers.org/help)
4. mcserv.org - **IDK**
5. topg.org - [https://topg.org/fr/voting_check](https://topg.org/fr/voting_check)
6. mineliste.fr - **IDK**

Voting sites verified by Azuriom but with endless loading:
1. serveurliste.com
2. trackyserver.com

Lesser-known voting sites not verified by Azuriom:
1. topminecraftservers.org - votifier: [https://topminecraftservers.org/faq.php](https://topminecraftservers.org/faq.php)
2. best-minecraft-servers.co - votifier: [https://best-minecraft-servers.co/help](https://best-minecraft-servers.co/help)
3. planetminecraft.com - **IDK**
4. crafty.gg - [https://crafty.gg/public-api#tag/Servers](https://crafty.gg/public-api#tag/Servers) AND [votifier](https://crafty.gg/tools/votifier)
5. minecraft.buzz - Votifier: [https://minecraft.buzz/about](https://minecraft.buzz/about)
6. servers-minecraft.net - [https://minecraft-server.net/api/docs/](https://minecraft-server.net/api/docs/) AND [Votifier](https://servers-minecraft.net/votifier-tester)
7. emeraldservers.com - **IDK**
8. fr.namemc.com - JSON API at the bottom of the page [https://fr.namemc.com/server/play.knightworld.fr](https://fr.namemc.com/server/play.knightworld.fr)
10. topmcservers.com - **IDK**

IDK : I don't know

**Comment by Bricec6** [comment]
Hello,

I'm a developer at serveurliste.com, the API isn't working at the moment _(due to infrastructure changes and updates)_.

We're working on it, Azuriom users have to remove the API check for the moment.

Thank you

**Comment by KnightWorldfr** [comment]
OK, I'll make a note of it. Do you have a correction date or is that not planned?

**Comment by Bricec6** [comment]
We are in the test period

**Comment by MrMicky-FR** [comment]
Please provide for each of the suggested vote website a link for the documentation for vote verification, because some of the mentioned websites doesn’t even offer an API so there is no way for Azuriom to verify the votes.

**Comment by KnightWorldfr** [comment]
I've updated my post, I've done the best I can, I hope it helps.

**Comment by MrMicky-FR** [comment]
For all the websites using Votifier, you should directly setup Votifier. All good for the others

**Comment by KnightWorldfr** [comment]
How do I configure votifier on the website? If I configure it on my minecraft server how will it communicate with the website for rewards etc?

**Comment by MrMicky-FR** [comment]
You should configure the rewards directly in Votifier as it’s an independent system

**Comment by KnightWorldfr** [comment]
ah yes but then for the top vote-getters of the month on the site, the votifier votes won't count? don't you have a way of adding the votifier parameters to the voting sites in azuriom so that the verification can be done on the site? x) I don't really know if that's possible? or using azlink to recover the votifier vote and sending back to the site that the verification is OK via azlink and votifier??

**Comment by MrMicky-FR** [comment]
For Votifier currently there is no existing solution as Votifier uses a non-standard protocol which would be not compatible with most web hosts (as only HTTP(S) is supported)

About the few remaining vote websites:
* serveur-minecraft.com & topg.org: we are not adding support for new **french** vote websites our-self as there is already plenty available, but a **pull request will be accepted**
* crafty.gg: I can't find any way to retrieve votes in the API: getting players doesn't show their upvotes, and it doesn't seem to have an API to find the upvotes of a server?
* servers-minecraft.net: the given link for the documentation is for minecraft-server.net, which is **already supported**

**Comment by KnightWorldfr** [comment]
Hello,

I actively use the websites serveur-minecraft.com and topg.org, and I would really like to set up automatic verification for these two platforms. I would be grateful for your assistance with this. As for the other sites, they are less important to me; my research was mainly intended to contribute to your development without any personal interest.

**Could you help me add automatic verification for the two sites mentioned?**

Regarding Votifier, wouldn't it be possible to use the AzLink plugin to detect the Votifier response and send the confirmation back to the website? We could add an option in the site settings to choose verification via Votifier or AzLink. I am convinced there is a viable solution :/
