### ISSUE TITLE
Suggested Improvement for Voting Reset Times

### ISSUE THREAD

**Issue by KnightWorldfr** [Azuriom/Plugin-Vote#99]
Some voting sites don't use a fixed delay, like every 1h30 or so, but instead reset at a specific time, such as midnight or 6 a.m. It would be helpful to have an option to check a box labeled "Every day at: X" and define "X" as the time when the vote resets. Currently, we can only set a fixed time interval. For example, if the votes reset every day at midnight and I vote at 11 p.m., I should be able to vote again after midnight.

**Comment by MrMicky-FR** [comment]
For which voting site?

**Comment by KnightWorldfr** [comment]
Unfortunately, I know there are at least 4 or 5 sites, including some already verified with Azuriom, but I wouldn't be able to name them. It would be complex to add options to the voting site edit page on Azuriom, such as "every..." and "every day at...". The idea would be to select these checkboxes to adjust the comparison method based on the time specified below. Currently, the "every..." option is set in minutes, and it would be up to you to determine how to handle the "every day at..." option
